var number = 10;

try{

  console.log(number);


}
catch(err){
  console.log(err.name);

  alert("هناك خطا في اكواد ضمن try");
}

